name = "Minecraft Modpack"
author = "tsea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59497a1697858714a49ad7aa2caca3b3b416e000d300ea412f0032defa901431"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
