name = "Minecraft Modpack"
author = "tsea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b292efffc56380c54da3d2a547f7a76842364105f882060c405ff1d0130ef7a"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
