name = "Minecraft Modpack"
author = "tsea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6e163e363dc80e760d946e10bb5e2a2eb2b8aad334964deec96bf509263126"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
