name = "Minecraft Modpack"
author = "tsea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23d4ca500348c77b61bea9548d55ab7f013d4b348e9d2f54211b87675d2e80d"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
