name = "Minecraft Modpack"
author = "tsea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03f5f94d090480751516526f8eb5018153f058fd039b36d20d2e752bb2760ed4"

[versions]
forge = "47.4.4"
minecraft = "1.20.1"
